version: '2'
services:

  presto-master:
    image: 'prestodb/centos6-oj8-openldap:${DOCKER_IMAGES_VERSION}'
    command: /docker/volumes/conf/docker/files/presto-launcher-wrapper.sh singlenode-ldap run
    extra_hosts:
       - "${LDAP_SERVER_HOST}:${LDAP_SERVER_IP}"

  application-runner:
    image: 'prestodb/centos6-oj8-openldap:${DOCKER_IMAGES_VERSION}'
    volumes:
      - ../../../conf/tempto/tempto-configuration-for-docker-ldap.yaml:/docker/volumes/tempto/tempto-configuration-local.yaml

  ldapserver:
    image: 'prestodb/centos6-oj8-openldap:${DOCKER_IMAGES_VERSION}'
